# Generated by Django 5.0.2 on 2024-04-26 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
    ]
