# Generated by Django 5.0.2 on 2024-05-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateWaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.CharField(blank=True, max_length=200, null=True)),
                ("store_pass", models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
